DROP TABLE MEMBER_BOOK;
DROP TABLE REVIEW;
DROP TABLE GOAL;
DROP TABLE READING_SESSION;
DROP TABLE BOOK_BADGE;
DROP TABLE BOOK_GENRE; 
DROP TABLE MEMBER;
DROP TABLE BOOK;
DROP TABLE AUTHOR;
DROP TABLE GENRE;
DROP TABLE BADGE;

CREATE TABLE MEMBER (
    UserID CHAR(4),
    FirstName VARCHAR(15),
    LastName VARCHAR(20),
    Phone CHAR(12),
    Email VARCHAR(50),
    UserName VARCHAR(30) NOT NULL,
    Password VARCHAR(128) NOT NULL,
    UNIQUE (UserName)
);

ALTER TABLE MEMBER ADD PRIMARY KEY (UserID);

CREATE TABLE AUTHOR (
    AuthorID CHAR(4),
    FirstName VARCHAR(15),
    LastName VARCHAR(20)
);

ALTER TABLE AUTHOR ADD PRIMARY KEY (AuthorID);

CREATE TABLE BOOK (
    BookID CHAR(4),
    AuthorID CHAR(4),
    BookTitle VARCHAR(60),
    BookDescription VARCHAR(200),
    CoverURL VARCHAR(255),
    PublihsedYear NUMERIC(4)
);

ALTER TABLE BOOK ADD PRIMARY KEY (BookID);

CREATE TABLE GENRE (
    GenreID CHAR(4),
    GenreName VARCHAR(50)
);

ALTER TABLE GENRE ADD PRIMARY KEY (GenreID);

CREATE TABLE BADGE (
    BadgeID CHAR(4),
    BageDescription VARCHAR(100),
    BadgeName VARCHAR(60)
);

ALTER TABLE BADGE ADD PRIMARY KEY (BadgeID);

CREATE TABLE REVIEW (
    ReviewID CHAR(4),
    UserID CHAR(4),
    BookID CHAR(4),
    Rating NUMERIC(1),
    ReviewDescription VARCHAR(500)
);

ALTER TABLE REVIEW ADD PRIMARY KEY (ReviewID);

CREATE TABLE MEMBER_BOOK (
    BookID CHAR(4),
    UserID CHAR(4),
    Status VARCHAR(11),
    StartDate DATE,
    EndDate DATE
);

ALTER TABLE MEMBER_BOOK ADD PRIMARY KEY (BookID, UserID);

CREATE TABLE GOAL (
    UserID CHAR(4),
    GoalID CHAR(4),
    GoalDescription VARCHAR(100),
    GoalStatus VARCHAR(11),
    StartDate DATE,
    EndDate DATE
);

ALTER TABLE GOAL ADD PRIMARY KEY (GoalID);

CREATE TABLE READING_SESSION (
    SessionID CHAR(4),
    BookID CHAR(4),
    UserID CHAR(4),
    Duration NUMERIC(4,1),
    SessionDate DATE
);

ALTER TABLE READING_SESSION ADD PRIMARY KEY (SessionID);

CREATE TABLE BOOK_BADGE (
    BookID CHAR(4),
    BadgeID CHAR(4)
);

ALTER TABLE BOOK_BADGE ADD PRIMARY KEY (BookID, BadgeID);

CREATE TABLE BOOK_GENRE (
    BookID CHAR(4),
    GenreID CHAR(4)
);

ALTER TABLE BOOK_GENRE ADD PRIMARY KEY (BookID, BadgeID);

ALTER TABLE MEMBER_BOOK
    ADD CONSTRAINT MEMBER_BOOK_BOOK FOREIGN KEY (BookID)
        REFERENCES BOOK (BookID); 
ALTER TABLE MEMBER_BOOK
    ADD CONSTRAINT MEMBER_BOOK_MEMBER FOREIGN KEY (UserID)
        REFERENCES MEMBER (UserID); 
        
ALTER TABLE REVIEW
    ADD CONSTRAINT REVIEW_MEMBER FOREIGN KEY (UserID)
        REFERENCES MEMBER (UserID);
ALTER TABLE REVIEW
    ADD CONSTRAINT REVIEW_BOOK FOREIGN KEY (BookID)
        REFERENCES BOOK (BookID);

ALTER TABLE BOOK
    ADD CONSTRAINT BOOK_AUTHOR FOREIGN KEY (AuthorID)
        REFERENCES AUTHOR (AuthorID);
    
ALTER TABLE BOOK_GENRE
    ADD CONSTRAINT BOOK_GENRE_BOOK FOREIGN KEY (BookID)
        REFERENCES BOOK (BookID);
ALTER TABLE BOOK_GENRE
    ADD CONSTRAINT BOOK_GENRE_GENRE FOREIGN KEY (GenreID)
        REFERENCES GENRE (GenreID);
        
ALTER TABLE BOOK_BADGE
    ADD CONSTRAINT BOOK_BADGE_BADGE FOREIGN KEY (BadgeID)
        REFERENCES BADGE (BadgeID);
ALTER TABLE BOOK_BADGE
    ADD CONSTRAINT BOOK_BADGE_BOOK FOREIGN KEY (BookID)
        REFERENCES BOOK (BookID);
    
ALTER TABLE READING_SESSION
    ADD CONSTRAINT READING_SESSION_BOOK FOREIGN KEY (BookID)
        REFERENCES BOOK (BookID);
ALTER TABLE READING_SESSION
    ADD CONSTRAINT READING_SESSION_MEMBER FOREIGN KEY (UserID)
        REFERENCES MEMBER (UserID);

ALTER TABLE GOAL
    ADD CONSTRAINT GOAL_MEMBER FOREIGN KEY (UserID)
        REFERENCES MEMBER (UserID);

COMMIT;